import { useState } from 'react';
const d={nome:'Fazenda São João',proprietario:'Gustavo',local:'Mato Grosso, BR',area:'450 hectares',plantios:[{cultura:'Soja',area:'200 ha',status:'Crescendo'},{cultura:'Milho',area:'150 ha',status:'Colheita'},{cultura:'Algodão',area:'100 ha',status:'Plantado'}],financeiro:[{mes:'Janeiro',receita:45000,despesa:28000,categoria:'Venda Soja',tipo:'receita'},{mes:'Fevereiro',receita:38000,despesa:32000,categoria:'Insumos',tipo:'despesa'},{mes:'Março',receita:62000,despesa:25000,categoria:'Venda Milho',tipo:'receita'},{mes:'Abril',receita:29000,despesa:41000,categoria:'Maquinário',tipo:'despesa'},{mes:'Maio',receita:75000,despesa:30000,categoria:'Venda Soja',tipo:'receita'},{mes:'Junho',receita:55000,despesa:27000,categoria:'Venda Algodão',tipo:'receita'},{mes:'Julho',receita:48000,despesa:35000,categoria:'Insumos',tipo:'despesa'},{mes:'Agosto',receita:90000,despesa:22000,categoria:'Venda Milho',tipo:'receita'},{mes:'Setembro',receita:67000,despesa:38000,categoria:'Mão de Obra',tipo:'despesa'},{mes:'Outubro',receita:83000,despesa:29000,categoria:'Venda Soja',tipo:'receita'},{mes:'Novembro',receita:71000,despesa:33000,categoria:'Venda Algodão',tipo:'receita'},{mes:'Dezembro',receita:95000,despesa:45000,categoria:'Venda Milho',tipo:'receita'}],alertas:[{tipo:'warning',msg:'Irrigacao em 2h'},{tipo:'info',msg:'Chuva amanha: 18mm'},{tipo:'success',msg:'Colheita favoravel'}]};
export default function App(){
const [logado,setLogado]=useState(false),[email,setEmail]=useState(''),[senha,setSenha]=useState(''),[secao,setSecao]=useState('dashboard'),[fMes,setFMes]=useState('Todos'),[fTipo,setFTipo]=useState('Todos');
const menu=[{id:'dashboard',label:'Dashboard'},{id:'plantios',label:'Plantios'},{id:'financeiro',label:'Financeiro'},{id:'alertas',label:'Alertas'},{id:'fazenda',label:'Minha Fazenda'}];
const fin=d.financeiro.filter(m=>(fMes==='Todos'||m.mes===fMes)&&(fTipo==='Todos'||m.tipo===fTipo));
const tR=fin.reduce((s,m)=>s+m.receita,0),tD=fin.reduce((s,m)=>s+m.despesa,0),luc=tR-tD;
const fmt=(v:number)=>'R$ '+v.toLocaleString('pt-BR');
if(!logado)return(<div className="login-bg"><div className="login-box"><div className="login-logo"><h1>AgroDigital</h1><p>Gestão inteligente do campo</p></div><div className="login-form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="fazenda@agrodigital.com"/></label><label>Senha<input type="password" value={senha} onChange={e=>setSenha(e.target.value)} placeholder="123456"/></label><button className="btn-login" onClick={()=>{if(email==='fazenda@agrodigital.com'&&senha==='123456')setLogado(true)}}>Entrar</button><p className="login-hint">Demo: fazenda@agrodigital.com / 123456</p></div></div></div>);
return(<div className="app-layout"><aside className="sidebar aberto"><div className="sidebar-header"><span className="logo-texto">AgroDigital</span></div><nav className="sidebar-nav">{menu.map(m=>(<button key={m.id} className={'nav-item '+(secao===m.id?'ativo':'')} onClick={()=>setSecao(m.id)}>{m.label}</button>))}</nav></aside><main className="main-content"><header className="topbar"><div><h2 className="topbar-titulo">{menu.find(m=>m.id===secao)?.label}</h2><p className="topbar-sub">{d.nome} - {d.local}</p></div><div className="topbar-usuario">{d.proprietario}</div></header><div className="conteudo">
{secao==='dashboard'&&(<div className="secao"><div className="cards-grid"><div className="card card-up"><div className="card-info"><p className="card-label">Temperatura</p><strong className="card-value">26C</strong></div></div><div className="card card-down"><div className="card-info"><p className="card-label">Humidade %</p><strong className="card-value">74</strong></div></div><div className="card card-stable"><div className="card-info"><p className="card-label">PH Solo</p><strong className="card-value">6.8</strong></div></div><div className="card card-up"><div className="card-info"><p className="card-label">Umidade Solo</p><strong className="card-value">52%</strong></div></div></div></div>)}
{secao==='plantios'&&(<div className="secao"><div className="painel"><h3>Plantios</h3><div style={{display:'flex',flexDirection:'column',gap:'16px'}}>{d.plantios.map((p,i)=>{const prog=p.status==='Colheita'?90:p.status==='Crescendo'?60:20;const cor=p.status==='Colheita'?'#f59e0b':p.status==='Crescendo'?'#22c55e':'#3b82f6';return(<div key={i} style={{background:'white',borderRadius:'12px',padding:'16px',boxShadow:'0 1px 4px rgba(0,0,0,0.08)'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:'8px'}}><strong>{p.cultura}</strong><span style={{background:cor,color:'white',borderRadius:'20px',padding:'2px 12px',fontSize:'13px'}}>{p.status}</span></div><div style={{color:'#666',marginBottom:'8px'}}>📍 {p.area}</div><div style={{display:'flex',justifyContent:'space-between',fontSize:'13px',marginBottom:'4px'}}><span>Progresso</span><span>{prog}%</span></div><div style={{background:'#e5e7eb',borderRadius:'99px',height:'8px'}}><div style={{width:prog+'%',background:cor,height:'8px',borderRadius:'99px'}}></div></div></div>);})}</div></div></div>)
{secao==='financeiro'&&(<div className="secao"><div className="fin-cards"><div className="fin-card fin-receita"><p className="fin-card-label">Total Receitas</p><strong className="fin-card-valor">{fmt(tR)}</strong></div><div className="fin-card fin-despesa"><p className="fin-card-label">Total Despesas</p><strong className="fin-card-valor">{fmt(tD)}</strong></div><div className={'fin-card '+(luc>=0?'fin-lucro':'fin-prejuizo')}><p className="fin-card-label">Lucro Liquido</p><strong className="fin-card-valor">{fmt(luc)}</strong></div><div className="fin-card fin-margem"><p className="fin-card-label">Margem</p><strong className="fin-card-valor">{tR>0?((luc/tR)*100).toFixed(1):0}%</strong></div></div><div className="painel"><div className="fin-filtros"><div className="fin-filtro-grupo"><label>Mes</label><select value={fMes} onChange={e=>setFMes(e.target.value)}><option>Todos</option>{d.financeiro.map(m=><option key={m.mes}>{m.mes}</option>)}</select></div><div className="fin-filtro-grupo"><label>Tipo</label><select value={fTipo} onChange={e=>setFTipo(e.target.value)}><option>Todos</option><option value="receita">Receita</option><option value="despesa">Despesa</option></select></div><button className="btn-limpar" onClick={()=>{setFMes('Todos');setFTipo('Todos')}}>Limpar</button></div><table className="tabela"><thead><tr><th>Mes</th><th>Categoria</th><th>Receita</th><th>Despesa</th><th>Saldo</th><th>Status</th></tr></thead><tbody>{fin.map(m=>{const s=m.receita-m.despesa;return(<tr key={m.mes}><td><strong>{m.mes}</strong></td><td>{m.categoria}</td><td className="verde">{fmt(m.receita)}</td><td className="vermelho">{fmt(m.despesa)}</td><td className={s>=0?'verde':'vermelho'}><strong>{fmt(s)}</strong></td><td><span className={'badge '+(s>=0?'badge-positivo':'badge-negativo')}>{s>=0?'Positivo':'Negativo'}</span></td></tr>);})}</tbody><tfoot><tr className="tabela-total"><td colSpan={2}><strong>TOTAL</strong></td><td className="verde"><strong>{fmt(tR)}</strong></td><td className="vermelho"><strong>{fmt(tD)}</strong></td><td className={luc>=0?'verde':'vermelho'}><strong>{fmt(luc)}</strong></td><td><span className={'badge '+(luc>=0?'badge-positivo':'badge-negativo')}>{luc>=0?'Lucro':'Prejuizo'}</span></td></tr></tfoot></table></div></div>)}
{secao==='alertas'&&(<div className="secao"><div className="painel"><h3>Alertas</h3>{d.alertas.map((a,i)=>(<div key={i} className={'alerta alerta-'+a.tipo}><p>{a.msg}</p></div>))}</div></div>)}
{secao==='fazenda'&&(<div className="secao"><div className="painel"><h3>Dados da Fazenda</h3><div className="fazenda-info"><div className="info-row"><span>Nome</span><strong>{d.nome}</strong></div><div className="info-row"><span>Proprietario</span><strong>{d.proprietario}</strong></div><div className="info-row"><span>Area</span><strong>{d.area}</strong></div><div className="info-row"><span>Local</span><strong>{d.local}</strong></div></div></div></div>)}
</div></main></div>);}
